/**
 * PWA Constants - AUTO-GENERATED FILE
 * 
 * This file is automatically generated at build time.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 * 
 * Generated at: 2025-07-07T00:01:18.023Z
 * Version: 0.1.0-3307c4a-20250707000118
 */

// Dynamic version for cache busting - changes with every build
export const PWA_VERSION = '0.1.0-3307c4a-20250707000118';

// Cache names with versioning strategy
export const CACHE_NAMES = {
  // Versioned caches - will be cleared on version change
  precache: `fleetops-precache-v${PWA_VERSION}`,  // App shell (HTML, CSS, JS)
  runtime: `fleetops-runtime-v${PWA_VERSION}`,    // API responses, dynamic content
  
  // Data caches - persist across versions (critical for field operations)
  equipment: 'fleetops-equipment-v1',  // Equipment specs, manuals, procedures
  telemetry: 'fleetops-telemetry-v1',  // Last 24hr sensor readings
} as const;

// Service Worker behavior configuration
export const PWA_CONFIG = {
  // Immediately activate new service worker
  // RATIONALE: Safety updates must apply without waiting
  skipWaiting: true,
  
  // Take control of all pages immediately
  // RATIONALE: Consistent experience across all tabs
  clientsClaim: true,
  
  // Reload pages when coming back online
  // RATIONALE: Ensure fresh telemetry data after offline period
  reloadOnOnline: true,
} as const;

// Build metadata for debugging
export const PWA_BUILD_INFO = {
  version: '0.1.0-3307c4a-20250707000118',
  packageVersion: '0.1.0',
  gitHash: '3307c4a',
  timestamp: '20250707000118',
  buildDate: '2025-07-07T00:01:18.023Z',
} as const;
